on: [push]
name: CI
env:
  AUTH: ${{secrets.USER_DEPLOY_REPO}}:${{secrets.PERSONAL_ACCESS_TOKEN}}
  REPO: ${{secrets.DEPLOY_REPO}}
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Configure git for private modules
        run: git config --global url."https://${AUTH}@github.com".insteadOf "https://github.com"
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test --race -v -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

  deploy_dev:
    needs: test
    if: github.ref == 'refs/branch/master'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev
        run: |
          curl -XPOST -u "${AUTH}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" \
          https://api.github.com/repos/${REPO}/dispatches --data '{"event_type": "dev"}'

  deploy_prod:
    needs: test
    if: contains(github.ref, 'tags')
    runs-on: ubuntu-latest
    steps:
      - name: Validate Tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v\d+\.\d+\.\d+$ ]]; then
              echo ::set-env name=DEPLOY_ENV::prod
          fi
      - name: Deploy Prod
        if: env.DEPLOY_ENV == 'prod'
        run: |
          curl -XPOST -u "${AUTH}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" \
          https://api.github.com/repos/${REPO}/dispatches --data '{"event_type": "prod"}'
